### ISSUE TITLE
Upgrade to Angular 2 Final Release (2.0.0)

### ISSUE THREAD

**Issue by maybeec** [oasp-forge/oasp4js-rev#12]

**Comment by RobertoGM** [comment]
I have been trying to implement the Router component ( #14 ) but there are some problems with the version of RC since router component it is receiving a lot of updates each version. Then I decided to also  upgrade to latest RC version and implement Router in that version, but I am having problems with the installation of the typings in the post-install probably because of the proxy here in Capgemini. I will continue researching a solution for both problems so i assign myself this issue too. In case i do not find any possible solution i will try to upgrade outside of Capgemini.

P.D: I got the last version from Angular web page QuickStart's package.json: https://angular.io/docs/ts/latest/quickstart.html

**Comment by cbeldacap** [comment]
Angular 2 team just released the latest version which has been named as RC6. I found an example of `package.json` updated to RC5.

[https://gist.github.com/squadwuschel/eed485e6afbbc879710402fb79233e98](url)

**Comment by cbeldacap** [comment]
It seems like the first real version of Anglar2 had been released, beyond from RC versions. 
https://angular.io/

**Comment by maybeec** [comment]
nice! so code will stabilize even better.

**Comment by cbeldacap** [comment]
Let's try this 2 steps for upgrading to final release
1. Update the coincident dependencies with this JSON file: 

(from Final Release)
[package.zip](https://github.com/oasp-forge/oasp4js-rev/files/474377/package.zip)

(from angular2-sample-app project about to be migrated)
[package.json.txt](https://github.com/oasp-forge/oasp4js-rev/files/476576/package_json.FR.txt)
1. Run the **npm** command:
   `npm install`
2. watch how it behaves with the current project

_note_: There are also some other upgrades, such as **typings** (1.0.4),  **typescript** (2.0.2) and **systemjs** (0.19.27)

**Comment by RobertoGM** [comment]
project upgraded and working in last angular 2 version (2.0.0 final release)
