### ISSUE TITLE
Table search does not work at all

### ISSUE THREAD

**Issue by maybeec** [oasp-forge/oasp4js-rev#19]
Searching for tables does not work for now. There are several issues:
- [ ] searching does not do anything
- [x] State should be a dropdown box, which allows selecting any valid state
- [x] table number should be a simple value. Currently, there are up and down buttons, which are simply nonsense here
- [x] the input fields seem to be text areas, which allow line breaks. Thus, pressing return will result in an empty input field, which is kind of strange as well as the fact, that the user will search for a string he could not even see.

**Comment by RobertoGM** [comment]
Table search component at the moment only purpose is provide a container for a form (defined outside the component for more flexibility) and 2 buttons to clear and search(search itself does not work because i did not think is worth to implement a front-end solution while we research a back-end implementation, but the "search" button does collect the form information).

The form is only a test so I did not care much about which input types I used. In the future I will configure a good looking and fully functional searching form.

Thank you for the comment!

**Comment by RobertoGM** [comment]
The problem with inputs and empty fields was with pressing enter key, which called "clearForm()" function, making blank the input value. Now if you press enter key, the component calls the function "doSearch()" and leaves the values untouched.

**Comment by RobertoGM** [comment]
table-search implemented server-side with the function provided. Seems like there is no function to search (server-side) the info in the tables kitchen
