### ISSUE TITLE
fix travis build

### ISSUE THREAD

**Issue by maybeec** [oasp-forge/oasp4js-rev#28]

**Comment by cbeldacap** [comment]
It seems like with the upgrading to 2.0.0 `karma.conf.js` no longer matched with Travis. I backed it up and looks good. Now the issue is the correct implementation of `.spec` files, which is getting little bit difficult due to the interrelation of components and services with modules, other components and so on. Still working on that.

**Comment by RobertoGM** [comment]
Finally, we got Travis and Karma working! :v:

**Comment by maybeec** [comment]
good job!
